/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bw_co_roguesystems_Hdbscan */

#ifndef _Included_bw_co_roguesystems_Hdbscan
#define _Included_bw_co_roguesystems_Hdbscan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bw_co_roguesystems_Hdbscan
 * Method:    initHdbscan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bw_co_roguesystems_Hdbscan_initHdbscan
  (JNIEnv *, jobject, jint);

/*
 * Class:     bw_co_roguesystems_Hdbscan
 * Method:    runImpl
 * Signature: ([[D)[I
 */
JNIEXPORT jintArray JNICALL Java_bw_co_roguesystems_Hdbscan_runImpl
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     bw_co_roguesystems_Hdbscan
 * Method:    reRunImpl
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_bw_co_roguesystems_Hdbscan_reRunImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     bw_co_roguesystems_Hdbscan
 * Method:    cleanHdbscan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bw_co_roguesystems_Hdbscan_cleanHdbscan
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
